# 抄自
# https://github.com/harryhare/udacity_cloud_devops_projects/blob/master/l4_circleci/.circleci/config.yml
# https://circleci.com/docs/2.0/hello-world/
# https://discuss.circleci.com/t/cron-job-every-x-hours/38039
version: 2.1
jobs:
  build:
    docker:
      - image: debian:latest # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: echo "hello world" # run the `echo` command
      - run:
          name: basic info
          command: |
            whoami
            pwd

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: dependencies
          command: |
            apt-get update
            apt-get -y install python3 python3-pip  python3-venv tesseract-ocr
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run app
          command: |
            . venv/bin/activate
            cd src && python3 service.py



