name: '(! test only) docker test'

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: docker test 1
        run: |
          docker run hello-world

      - name: docker test 2
        run: |
          docker run -d -p 8080:80 --name=nginx nginx

      - name: docker test 3
        run: |
          curl localhost:8080

      - name: docker test 4
        run: |
          docker stop nginx