name: '(! test only) get credit ubuntu'

on:
  workflow_dispatch:
#  schedule:
#    - cron: '45 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo /bin/bash prepare.sh

      - name: run the script
        run: |
          cd src && python3 service.py "${{ secrets.USERS }}"
