name: '(! test only) get credit macos'

on:
  workflow_dispatch:
#  schedule:
#    - cron: '45 0 * * *'

jobs:
  run:
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          brew install  tesseract
          pip3 install -r requirements.txt

      - name: run the script
        run: |
          cd src && python3 service.py "${{ secrets.USERS }}"
